-- LIMPIAMOS EL CACHE 
FLUSH TABLES;

-- HABILITAMOS PROFILING
SET profiling = 1;
-- EJECUTAMOS LA CONSULTA 3 VECES
 SELECT * FROM EMPLEADO WHERE DNI = '00100522';
 SELECT * FROM EMPLEADO WHERE DNI = '00100522';
 SELECT * FROM EMPLEADO WHERE DNI = '00100522';

 SELECT * FROM LEGAJO WHERE id BETWEEN 1 AND  439000;
 SELECT * FROM LEGAJO WHERE id BETWEEN 1 AND  439000;
 SELECT * FROM LEGAJO WHERE id BETWEEN 1 AND  439000;

 SELECT * FROM empleado e
 INNER JOIN legajo l on l.id = e.legajo
 WHERE l.estado = 'INACTIVO';

 SELECT * FROM empleado e
 INNER JOIN legajo l on l.id = e.legajo
 WHERE l.estado = 'INACTIVO';

 SELECT * FROM empleado e
 INNER JOIN legajo l on l.id = e.legajo
 WHERE l.estado = 'INACTIVO';

-- NOSTRAMOS LOS RESULTADOS
SHOW PROFILES;


